apiVersion: v1
kind: ReplicationController
metadata:
  name: myappreplicaset
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: myfirstpod
      labels:
        apps: myapp
        type: front-end
    spec:
      containers:
      - name: nginx-container
        image: nginx
  replicas: 3
